insert into cities(id,name) values('1','Bogotá');
insert into cities(id,name) values('2','Medellín');
insert into cities(id,name) values('3','Cali');
insert into cities(id,name) values('4','Barranquilla');
insert into cities(id,name) values('5','Cartagena');
insert into members(id,name) values('1','JiU');
insert into members(id,name) values('2','SuA');
insert into members(id,name) values('3','Siyeon');
insert into members(id,name) values('4','Handong');
insert into members(id,name) values('5','Yoohyeon');
insert into members(id,name) values('6','Dami');
insert into members(id,name) values('7','Gahyeon');
UPDATE blog_user SET is_admin=True WHERE username='DongnutLa';
UPDATE blog_user SET is_staff=True WHERE username='DongnutLa';