"""profilepicture

Revision ID: 0c84e489683d
Revises: b735120d0962
Create Date: 2021-11-07 17:20:55.498956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c84e489683d'
down_revision = 'b735120d0962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_user', sa.Column('profile_pic_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_user', 'profile_pic_name')
    # ### end Alembic commands ###
