"""Added social to users

Revision ID: 43af5d6ff7b4
Revises: 0c84e489683d
Create Date: 2021-11-08 21:25:54.773498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43af5d6ff7b4'
down_revision = '0c84e489683d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_user', sa.Column('facebook', sa.String(length=80), nullable=True))
    op.add_column('blog_user', sa.Column('twitter', sa.String(length=80), nullable=True))
    op.add_column('blog_user', sa.Column('instagram', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_user', 'instagram')
    op.drop_column('blog_user', 'twitter')
    op.drop_column('blog_user', 'facebook')
    # ### end Alembic commands ###
