"""init

Revision ID: b735120d0962
Revises: 
Create Date: 2021-11-06 20:13:44.286379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b735120d0962'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album', sa.String(length=256), nullable=False),
    sa.Column('album_image_name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('songs', sa.Text(), nullable=True),
    sa.Column('producers', sa.Text(), nullable=True),
    sa.Column('spotify', sa.String(), nullable=True),
    sa.Column('youtube', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('image_name', sa.String(length=256), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fanmade', sa.Boolean(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=True)
    op.create_table('album_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('pc_type', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('lastname', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('confirm', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photocard_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('pc_type_id', sa.Integer(), nullable=True),
    sa.Column('pc_name', sa.String(length=256), nullable=False),
    sa.Column('pc_image_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['pc_type_id'], ['album_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pc_name')
    )
    op.create_table('photocard_exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['blog_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('title_slug', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('image_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['blog_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_slug')
    )
    op.create_table('user_albums',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['blog_user.id'], )
    )
    op.create_table('user_bias',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bias_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bias_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['blog_user.id'], )
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_username', sa.String(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['blog_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pcex_pcdb_from',
    sa.Column('pc_ex_id', sa.Integer(), nullable=True),
    sa.Column('pc_db_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pc_db_id'], ['photocard_db.id'], ),
    sa.ForeignKeyConstraint(['pc_ex_id'], ['photocard_exchange.id'], )
    )
    op.create_table('pcex_pcdb_to',
    sa.Column('pc_ex_id', sa.Integer(), nullable=True),
    sa.Column('pc_db_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pc_db_id'], ['photocard_db.id'], ),
    sa.ForeignKeyConstraint(['pc_ex_id'], ['photocard_exchange.id'], )
    )
    op.create_table('user_exchange_interest',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pc_exchange_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pc_exchange_id'], ['photocard_exchange.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['blog_user.id'], )
    )
    op.create_table('user_photocards',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('photocard_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photocard_id'], ['photocard_db.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['blog_user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_photocards')
    op.drop_table('user_exchange_interest')
    op.drop_table('pcex_pcdb_to')
    op.drop_table('pcex_pcdb_from')
    op.drop_table('comment')
    op.drop_table('user_bias')
    op.drop_table('user_albums')
    op.drop_table('post')
    op.drop_table('photocard_exchange')
    op.drop_table('photocard_db')
    op.drop_table('gallery')
    op.drop_table('blog_user')
    op.drop_table('album_type')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_table('product')
    op.drop_table('members')
    op.drop_table('events')
    op.drop_table('cities')
    op.drop_table('album')
    # ### end Alembic commands ###
